# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    build:
      context: .
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    command: npm run dev
    ports:
      - 4000:4000
      - 5555:5555
    depends_on:
      - db
      - redis
    expose:
      - 5555
      - 4000

  db:
    image: postgres
    ports:
      - '5432:5432'
    expose:
      - 5432
    env_file:
      - .env

  redis:
    image: redis
    ports:
      - '6379:6379'
