version: '3.8'

services:
  api:
    build:
      context: .
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    container_name: api
    command: npm start
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    ports:
      - '4000:4000'
    depends_on:
      - db
    links:
      - db
    expose:
      - '4000'

  test:
    build:
      context: .
    volumes:
      - .:/test
    stdin_open: true
    tty: true
    container_name: tests
    command: npm test
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    depends_on:
      - db
    links:
      - db

  prisma:
    build:
      context: .
    volumes:
      - .:/prisma
    stdin_open: true
    tty: true
    command: npx prisma studio
    ports:
      - '5555:5555'
    expose:
      - '5555'
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public

  db:
    image: postgres
    ports:
      - '5432:5432'
    expose:
      - 5432
    env_file:
      - .env
